name: Deploy to Scaleway Serverless Containers

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: ${{ secrets.SCW_DEFAULT_REGION }}
      REGISTRY_ENDPOINT: rg.${{ secrets.SCW_DEFAULT_REGION }}.scw.cloud
      REGISTRY_NAMESPACE: ${{ secrets.SCW_REGISTRY_NAMESPACE }}
      IMAGE_NAME: chatbot-backend
      IMAGE_TAG: sha-${{ github.sha }}
      IMAGE_URI: rg.${{ secrets.SCW_DEFAULT_REGION }}.scw.cloud/${{ secrets.SCW_REGISTRY_NAMESPACE }}/chatbot-backend:sha-${{ github.sha }}
      SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          save-config: true
          export-config: true

      - name: Login to Scaleway Container Registry
        run: scw registry login

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_URI }}
            ${{ env.REGISTRY_ENDPOINT }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest

      - name: Update container image and deploy
        run: |
          scw container container update \
            container-id=${{ secrets.SCW_CONTAINER_ID }} \
            registry-image=${{ env.IMAGE_URI }} \
            port=8080 \
            protocol=http1
          scw container container deploy container-id=${{ secrets.SCW_CONTAINER_ID }}